### PR TITLE
chore: Make output determinist/reproducible

### PR DESCRIPTION
**Pull request by ainar**
Hey,
I made the pipeline fully determinist by bypassing some undefined behaviors of Python.
You were right in the TODO saying that the orders determine the output.
But in Python, the `set`s are unordered, and iterating over them yields undetermined results. Same for `map_unordered` of Synpp/multiprocessing's Pool. So, I managed to reorder things again after such operations.
I also manually removed the date (replaced it with a placeholder) of the GPKG files, which are automatically set to the date of execution.

All these modifications have made the output digests comparison possible.

Another modification: I avoided creating an HDF file for BDTOPO and census. The HDF files were different at each run (I suspect a date thing there too.) I don't know if there was a purpose for that, but it seems that using the cache does work...

Aina

### CODE REVIEW

**Comment by sebhoerl** [comment]
Thanks a lot, I'll have a closer look once #166 is merged. 

Yes, we were also wondering about the HDF part recently. I guess it is some artifact of an old version.

**Review by sebhoerl — APPROVED** [review]

**Comment by sebhoerl** [comment]
`LGTM`, please merge in `develop` :)

**Comment by sebhoerl** [comment]
Hm, it looks like Linux is passing, but there is a hash that is not correct on Windows. Strange, but maybe this is just randomness and I have introduced some additional source with the PR that I have merged before?

**Comment by sebhoerl** [comment]
Ok great! But please revert the last changes about the case, because this is actually how the files are called:
https://www.insee.fr/fr/statistiques/6456056

**Comment by ainar** [comment]
> Ok great! But please revert the last changes about the case, because this is actually how the files are called: https://www.insee.fr/fr/statistiques/6456056

I just downloaded it, it is really in uppercase except for "csv"...
image

**Comment by sebhoerl** [comment]
There are two options, one indicating the name of the zip (must remain upper case, you changed it) and one for the CSV inside the zip, which is already lowercase. The pipeline now reads directly from the zip, but pandas needs the internal name because there are two files inside.

**Comment by ainar** [comment]
> There are two options, one indicating the name of the zip (must remain upper case, you changed it) and one for the CSV inside the zip, which is already lowercase. The pipeline now reads directly from the zip, but pandas needs the internal name because there are two files inside.

But the CSV inside the zip is also uppercase, no? (See my screenshot: `FD_MOBPRO_2019.csv` and not FD_mobpro_2019.csv)

**Comment by sebhoerl** [comment]
Wait, actually, I mixed it up in my comment. You changed the zip name from lower case to upper case. I just saw that on the INSEE website it is lowercase:

image

But then once you click it redirects to an upper case, file name, ok ;) But somehow last time I downloaded it I ended up with the lower case names.

**Comment by ainar** [comment]
Yes, actually I noticed it as it did throw an error on my side because the file was not found (I use Ubuntu).

**Comment by sebhoerl** [comment]
Ok great, so this can be merged. Thanks a lot!

**Pull request merged**
