### PR TITLE
fix: Properly treat non-movers in EDGT 44

### PR DESCRIPTION
**Pull request by LeonardoLuquezi**
Select people who : 

 1. Fully awnsered the questionary (PENQ = 1) 
 2. and made at least one trip (P19 = 1) 
 3. or stayed at home (P19 =2)
 
All persons with PENQ == 1 match the 2 and 3 conditions but code is  written to make it explicit (counts :  all persons : 29496 ;  filtered persons : 20799)

### CODE REVIEW

**Comment by sebhoerl** [comment]
Just one remark (you tell if this applies here or not): For other EMDs, the structure is as follows:

- If I would look at all the persons coming out of `*hts*.cleaned` I could compare with INSEE population totals and I would get approximately the correct distribution (by age, gender, ...)
- However, this may also include persons that are not fully represented (for instance, ENTD has all household members in the persons, but then only activity chains for one reference person)
- After, `*hts*.filtered` provides those people which are actually relevant for the mobility analysis (having a chain, or non-movers) with the respective weights that are usually provided with the surveys

For you to say if this update maintains this logic ;-)

**Comment by sebhoerl** [comment]
I think this is more or less what you're doing for the EDGT now:
https://github.com/eqasim-org/ile-de-france/blob/develop/data/hts/entd/reweighted.py

**Comment by Nitnelav** [comment]
yeah this PR might not be need after all, but we'll run some tests to double check.
cheers

**Comment by LeonardoLuquezi** [comment]
Hello ! Thank you for your remark. I propose a new uptade to better consider people who fully awnsered the questionary and stayed at home (non-movers). It was done by setting their number of trips equal to 0 at the `cleaned.py` stage using PENQ (called "travel_respondent") variable. Then they will be filtered at `reweighted.py` as you mentioned.

**Comment by sebhoerl** [comment]
Great! :)

**Pull request merged**
