### PR TITLE
update dependencies in evironment.yml

### PR DESCRIPTION
**Pull request by Nitnelav**
The VSCode python debugger stopped working with python 3.6 recently. So I tried to create a new environment and it seams to work so far. I may have broke stuff and will update this PR if I encouter anything but so far so good...
Also the `python-Levenshtein` dependency doesn't install properly on windows at least so using `python-Levenshtein-wheels` fixes that also.

### CODE REVIEW

**Comment by sebhoerl** [comment]
Can you explain again what is the problem there? Actually, I was intentionally putting version numbers there because we noticed that for different versions of conda (especially on different operating systems) different packages got resolved, and then we ended up, for instance, with a geopandas in one version on one system and another one on another system - one having some methods already included, the other one not. But the biggest issue is that conda will always try to find the newest packages, which means that the `environment.yml` now is ambiguous. If I use the same `environment.yml` in two weeks, I may have different versions of the packages than now and things may break. 

So I'm fine with updating versions, but we should keep distinct version numbers.

**Comment by sebhoerl** [comment]
Actually, if I understand correctly, the issue was Python 3.6? In any case, we should also put Python and a version number explicitly in the `environment.yml`.

**Comment by Nitnelav** [comment]
Yes sorry I just threw that PR quickly after fixing my issue (yes it's python 3.6, need python >= 3.7 for vscode to debug).
I agree that fixing version numbers is the best approach, I will rework that PR

**Comment by Nitnelav** [comment]
ok I give up, I didn't manage to figure out something that works both on my machine and in the tests ... I'll be content with updating the python version manually after every git clone.

**Pull request closed without merging**
